[package]
name = "todolistcli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.11", features = ["derive", "cargo"] }
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
rusqlite = { version = "0.30.0", features = ["bundled"] }
